title: TheCleverEdge
author: susanne mistric
email: svmistric@waketech.edu
description: > # this means to ignore newlines until "baseurl:"
Always be curious

# social links
twitter_thatwebweweave: ThatWebWeWeave
github_susannetics:  susannetics

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
